# Generated by Django 3.0.7 on 2024-06-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('apellido_cli', models.CharField(max_length=150)),
                ('email_cli', models.EmailField(max_length=254)),
                ('telefono_cli', models.CharField(max_length=15)),
                ('fecha_Reguistro_cli', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_menu', models.CharField(max_length=100)),
                ('descripcion_menu', models.TextField()),
                ('precio_menu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('promociones_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pro', models.TextField()),
                ('fecha_inicio_pro', models.DateField()),
                ('fecha_fin_pro', models.DateField()),
                ('descuento_pro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('numero_personas_reserva', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones_Menus',
            fields=[
                ('promocionMenu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Menus')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Promociones')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Ventas',
            fields=[
                ('detalle_venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_venta', models.IntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Menus')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Reservas',
            fields=[
                ('detalle_reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Menus')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Reservas')),
            ],
        ),
    ]
