# Generated by Django 3.0.7 on 2024-06-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_auto_20240601_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo_Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_re', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision_re', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Clientes')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.Reservas')),
            ],
        ),
    ]
