# Generated by Django 3.0.7 on 2024-06-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0003_recibo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cedula_cli',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
