# Generated by Django 3.0.7 on 2024-06-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0004_clientes_cedula_cli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesas',
            old_name='capacidad',
            new_name='capacidad_mes',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='disponibilidad',
            new_name='disponibilidad_mes',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='estado',
            new_name='estado_mes',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='id',
            new_name='id_mesa',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='numero',
            new_name='numero_mes',
        ),
    ]
