# Generated by Django 3.0.7 on 2024-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0006_auto_20240605_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='disponibilidad_mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='estado_mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
