# Generated by Django 3.0.7 on 2024-06-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0007_auto_20240605_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesas',
            name='disponibilidad_mes',
        ),
    ]
