# Generated by Django 3.0.7 on 2024-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0008_remove_mesas_disponibilidad_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado_reserva',
            field=models.CharField(max_length=20),
        ),
    ]
