# Generated by Django 3.2.25 on 2024-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0010_auto_20240611_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo_reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
