# Generated by Django 3.2.25 on 2024-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0011_alter_recibo_reserva_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='categoria_menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='disponibilidad_menu',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
