# Generated by Django 3.2.25 on 2024-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0012_auto_20240617_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='fotos_menu',
            field=models.FileField(blank=True, null=True, upload_to='menus'),
        ),
    ]
