# Generated by Django 3.2.25 on 2024-06-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0013_menus_fotos_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='disponibilidad_menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
