# Generated by Django 3.2.25 on 2024-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0014_alter_menus_disponibilidad_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='precio_menu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
