# Generated by Django 3.2.25 on 2024-06-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0015_alter_menus_precio_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='total_venta',
            field=models.IntegerField(),
        ),
    ]
